[package]
name = "tray"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.24"      # Check for the latest version on crates.io
objc = "0.2"

[package.metadata.bundle]
identifier = "com.example.tray"